version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-app-api
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=financeapp
      - JWT_SECRET=sua_chave_secreta_aqui
      - JWT_EXPIRATION=86400
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./:/app
      - /app/node_modules
    command: >
      sh -c "npm run start:dev"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: finance-app-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=financeapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata: 